spring.datasource.url=${url:jdbc:mysql://localhost:3306/vedrunasite?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC}
spring.datasource.username=${user:root}
spring.datasource.password=${pass:root}
spring.jpa.hibernate.ddl-auto=validate
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.security.user.name=admin
spring.security.user.password=admin

