spring.datasource.url=${url:jdbc:mysql://localhost:3306/vedrunasite?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC}
spring.datasource.username=${user:root}
spring.datasource.password=${pass:root}
spring.jpa.hibernate.ddl-auto=validate
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.security.user.name=admin
spring.security.user.password=admin
spring.cache.type=simple

# Configuración de correo
mail.host=smtp.gmail.com
mail.port=587
mail.username=${MAIL_USERNAME}  # Utiliza variable de entorno para el usuario
mail.password=${MAIL_PASSWORD}  # Utiliza variable de entorno para la contraseña

# Configuración de propiedades adicionales de SMTP
mail.properties.mail.smtp.auth=true
mail.properties.mail.smtp.starttls.enable=true

# Correo del administrador
app.admin-email=diapasgar@gmail.com
