
spring.datasource.url=jdbc:mysql://dianapg.mysql.database.azure.com:3306/vedrunasite?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username=dianapg
spring.datasource.password=M01d1a17*

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

spring.security.user.name=admin
spring.security.user.password=admin

spring.cache.type=simple

# Configuración de correo
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

# Configuración de propiedades adicionales de SMTP
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Correo del administrador
app.admin-email=diapasgar@gmail.com

# Conexion a API Expo Push
expo.push.api.url=https://exp.host/--/api/v2/push/send
expo.push.api.key=default-api-key


logging.level.org.springframework.web=DEBUG
logging.level.io.swagger=DEBUG
logging.level.org.springdoc=DEBUG

